schema:
  - "https://graphql.contentful.com/content/v1/spaces/${CONTENTFUL_SPACE_ID}/environments/${CONTENTFUL_ENVIRONMENT}":
      headers:
        authorization: Bearer ${CONTENTFUL_PREVIEW_ACCESS_TOKEN}